name: as3_to_dart
version: 0.1.0
author: Nils Döhring <nilsdoehring@gmail.com>
description: Pure Actionscript to Dart Conversion Helper. 'pub global' Edition.
homepage: https://github.com/blockforest/actionscript-to-dart-pubglobal
environment:
  sdk: '>=1.6.0-dev'
dependencies:
  args: any
  path: any