name: acanvas_actionscript_converter
version: 0.7.0
author: Nils Döhring <nilsdoehring@gmail.com>
description: Pure Actionscript to StageXL Conversion Helper.
homepage: https://github.com/acanvas/acanvas-actionscript-converter
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  args: any
  path: any
executables:
  acanvas_converter: null